site_name: Software emulator PEE30
theme:
  name: material
  
plugins:
    - mkdocs-video
markdown_extensions:
- pymdownx.tabbed:
    alternate_style: true 
- toc
- tables
- admonition
- pymdownx.details
- pymdownx.superfences
extra_css:
 - css/Tabelstyling.css

nav:
    - Home: 'index.md'
    - 'Omgeving opzetten' : 'omgeving_opzetten.md'
    - 'Layout en navigatie van het emulatie programma': 'Layout_en_navigatie.md'
    - 'Testen':
        - 'MCU emulatie': 'MCU_emulatie.md'
        - 'Aandrijving emulatie': 'aandrijving_emulatie.md'
        - 'Belasting emulatie': 'belasting_emulatie.md'
    - Datacommunicatie:
        - 'Afspraken datacommunicatie' : 'afspraken_datacommunicatie.md'
        - 'Pin-out Breakoutbord' : 'pin_out_breakoutbord.md'
        - 'Registers en slave adressen I2C' :
           - 'Uitleg' : 'registers.md'
           - 'I2C Registermap aandrijving' : 'registers_aandrijving.md'
           - 'I2C Registermap belasting' : 'registers_belasting.md'
           
    - Over het project:
        - 'Licentie': 'license.md'
        - 'Bijdragers/Contribuanten': 'Bijdragers.md'
